plugins {
    id "com.android.application" version "9.0.1" apply false
    id "org.jetbrains.kotlin.android" version "2.2.20" apply false
}

subprojects {
    afterEvaluate { project ->
        if (project.hasProperty("android")) {
            project.android {
                compileSdkVersion 36
                if (project.android.hasProperty("compileSdk")) {
                    compileSdk = 36
                }
                compileOptions {
                    sourceCompatibility JavaVersion.VERSION_21
                    targetCompatibility JavaVersion.VERSION_21
                }
            }
        }
        tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).configureEach {
            kotlinOptions {
                jvmTarget = "21"
            }
        }
    }
}
